# ClkÔºàÊùøÂ≠ê‰?äÁ?ÑGCLKÔº?

# Rst(?ùøÂ≠ê‰?äÁ?ÑBTNU)
set_property PACKAGE_PIN F22 [get_ports rst]
set_property IOSTANDARD LVCMOS33 [get_ports rst]

set_property PACKAGE_PIN Y19 [get_ports vga_vs]
set_property IOSTANDARD LVCMOS33 [get_ports vga_vs]

set_property PACKAGE_PIN AA19 [get_ports vga_hs]
set_property IOSTANDARD LVCMOS33 [get_ports vga_hs]

set_property PACKAGE_PIN V20 [get_ports {vga_r[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_r[0]}]
set_property PACKAGE_PIN U20 [get_ports {vga_r[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_r[1]}]
set_property PACKAGE_PIN V19 [get_ports {vga_r[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_r[2]}]
set_property PACKAGE_PIN V18 [get_ports {vga_r[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_r[3]}]

set_property PACKAGE_PIN AB22 [get_ports {vga_g[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_g[0]}]
set_property PACKAGE_PIN AA22 [get_ports {vga_g[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_g[1]}]
set_property PACKAGE_PIN AB21 [get_ports {vga_g[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_g[2]}]
set_property PACKAGE_PIN AA21 [get_ports {vga_g[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_g[3]}]

set_property PACKAGE_PIN Y21 [get_ports {vga_b[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_b[0]}]
set_property PACKAGE_PIN Y20 [get_ports {vga_b[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_b[1]}]
set_property PACKAGE_PIN AB20 [get_ports {vga_b[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_b[2]}]
set_property PACKAGE_PIN AB19 [get_ports {vga_b[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_b[3]}]




set_property IOSTANDARD LVCMOS33 [get_ports {cmd[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmd[0]}]
set_property PACKAGE_PIN H22 [get_ports {cmd[1]}]
set_property PACKAGE_PIN G22 [get_ports {cmd[0]}]



set_property IOSTANDARD LVCMOS33 [get_ports {addr[18]}]
set_property IOSTANDARD LVCMOS33 [get_ports {addr[17]}]
set_property IOSTANDARD LVCMOS33 [get_ports {addr[16]}]
set_property IOSTANDARD LVCMOS33 [get_ports {addr[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {addr[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {addr[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {addr[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {addr[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {addr[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {addr[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {addr[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {addr[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {addr[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {addr[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {addr[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {addr[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {addr[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {addr[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {addr[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_in[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_in[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_in[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_in[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_in[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_in[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_in[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_in[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_in[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_in[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_in[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_in[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports clk_25mHz]
set_property PACKAGE_PIN Y18 [get_ports clk_25mHz]
set_property PACKAGE_PIN U17 [get_ports {addr[18]}]
set_property PACKAGE_PIN V17 [get_ports {addr[17]}]
set_property PACKAGE_PIN AA17 [get_ports {addr[16]}]
set_property PACKAGE_PIN AB17 [get_ports {addr[15]}]
set_property PACKAGE_PIN AA16 [get_ports {addr[14]}]
set_property PACKAGE_PIN AB16 [get_ports {addr[13]}]
set_property PACKAGE_PIN V14 [get_ports {addr[12]}]
set_property PACKAGE_PIN V15 [get_ports {addr[11]}]
set_property PACKAGE_PIN V13 [get_ports {addr[10]}]
set_property PACKAGE_PIN W13 [get_ports {addr[9]}]
set_property PACKAGE_PIN W15 [get_ports {addr[8]}]
set_property PACKAGE_PIN Y15 [get_ports {addr[7]}]
set_property PACKAGE_PIN Y14 [get_ports {addr[6]}]
set_property PACKAGE_PIN AA14 [get_ports {addr[5]}]
set_property PACKAGE_PIN Y13 [get_ports {addr[4]}]
set_property PACKAGE_PIN AA13 [get_ports {addr[3]}]
set_property PACKAGE_PIN AB14 [get_ports {addr[2]}]
set_property PACKAGE_PIN AB15 [get_ports {addr[1]}]
set_property PACKAGE_PIN U14 [get_ports {addr[0]}]
set_property PACKAGE_PIN U22 [get_ports {data_in[11]}]
set_property PACKAGE_PIN V22 [get_ports {data_in[10]}]
set_property PACKAGE_PIN W22 [get_ports {data_in[9]}]
set_property PACKAGE_PIN W20 [get_ports {data_in[8]}]
set_property PACKAGE_PIN W21 [get_ports {data_in[7]}]
set_property PACKAGE_PIN AA18 [get_ports {data_in[6]}]
set_property PACKAGE_PIN W17 [get_ports {data_in[5]}]
set_property PACKAGE_PIN W18 [get_ports {data_in[4]}]
set_property PACKAGE_PIN W16 [get_ports {data_in[3]}]
set_property PACKAGE_PIN Y16 [get_ports {data_in[2]}]
set_property PACKAGE_PIN U15 [get_ports {data_in[1]}]
set_property PACKAGE_PIN U16 [get_ports {data_in[0]}]



set_property IOSTANDARD LVCMOS33 [get_ports all_ready]
set_property PACKAGE_PIN T22 [get_ports all_ready]

